Profiel Hans toegevoegd
mstack/online-profiles pull request #15
Opened 2018-12-05 14:18 UTC by henthoven

2018-12-05 14:21 UTC, StefH requested changes
please fix it

2018-12-05 14:21 UTC, StefH commented on hans.html
> +                <div class="item">
voeg hier ... toe (zie profiel van stef)

2018-12-05 14:28 UTC, henthoven commented on hans.html
> +                <div class="item">
Toegevoegd...

2018-12-06 06:47 UTC, StefH approved these changes

2018-12-06 06:48 UTC, merged